#!/bin/bash
#
# Opens a file in vim, moves to the last line,
# and enters insert mode.
#
# Could probably just be an alias, but is 
# integral to some scripts so it's here for now.

vim '+ normal G$' +star "$1"
