#!/bin/bash

# 50toggleWifi
#
# toggles wifi when eithernet goes up or down.
# belongs in /etc/NetworkManager/deispatcher.d
# symlink there
case "$1" in
	enp0s25)
		if [ "$2" == up ]; then
			nmcli radio wifi off
		elif [ "$2" == down ]; then
			nmcli radio wifi on
		fi
		;;
esac
